### ISSUE TITLE
Cannot pickle objects of type TextWorldExpressEnv

### ISSUE THREAD

**Issue by HRezaei** [cognitiveailab/TextWorldExpress#13]
The `TextWorldExpressEnv` objects have two attributes (`server` and `_gateway`), that make it impossible to pickle the object. 

```python
import pickle
from textworld_express import TextWorldExpressEnv

env = TextWorldExpressEnv(envStepLimit=100)
env.load(gameName="twc", gameParams="numLocations=3, includeDoors=1")

file = open('/tmp/test', 'wb')
pickle.dump(env, file)

TypeError: cannot pickle '_thread.RLock' object
```

But if we remove these two properties, then dump succeeds without error:
```
del env.server
del env._gateway
pickle.dump(env, file)
```

Is there any workaround for this?

**Comment by PeterAJansen** [comment]
Hi @HRezaei , thanks for our question. 

One of the reasons TextWorldExpress is so fast is that it's written in heavily profiled Scala, where the Python interface is provided from some binders (that use a client/server architecture over sockets).   That's likely where the difficulty pickling comes through. 

That being said, all TextWorldExpress games should be completely deterministic -- if you initialize a game with the exact same generation parameters, seed, etc., and play back the exact same action sequence, then the game should be in an identical state.  In this way you could serialize a given game state by storing these parameters (game name, generation parameters, seed, and action sequence the agent has taken so far), and "deserialize" this by simply reinitializing a game with the same parameters and playing back the sequence (which should be very fast).  

@MarcCote and I were discussing this and we're going to look into whether it makes sense to add these serialize/deserialize functions directly into TextWorldExpress, since it seems like a common use case.

**Comment by MarcCote** [comment]
Hi @HRezaei, have a look at this #16. While it doesn't directly support pickling, you can easily pickle the output of `env.serialize()`, e.g.
```python
import pickle
env = TextWorldExpressEnv()
env.reset(gameName="cookingworld", seed=42)
env.step("look around")
state = env.serialize()
cloned_state = pickle.loads(pickle.dumps(state))
new_env = TextWorldExpressEnv.deserialize(cloned_state)
assert env.getRunHistory() == new_env.getRunHistory()
```
